### ISSUE TITLE
Collides with UNIX/coreutils "link"

### ISSUE THREAD

**Issue by Happy-Ferret** [sindresorhus/terminal-link-cli#1]
While I'm sure this is a great tool, the name is a bit ill chosen.
``link`` already exists in most environments, where it's used to create a hard link from an existing directory entry to a new directory entry (calling the ``link`` syscall internally).

I'm on Windows and even here this is an issue for most serious developers who have MinGW32/MSys2 aliased from their cmd.

**Comment by LitoMore** [comment]
Same issue here.

<img src="https://user-images.githubusercontent.com/8186898/38452142-96685b66-3a70-11e8-9211-6305fd84b5a3.png" width="50%" height="50%" />

I think `terminal-link` is better than `link`.

**Comment by Happy-Ferret** [comment]
Or term-link.
Or tlink. Anything that isn't already taken, really.
